# Compile Common.py
python:
	python3 -m compileall Common.py

# http users
userlist:
	htpasswd -bc userlist demo 99demo
	htpasswd -b userlist paul 99paul
	htpasswd -b userlist john 99john
	htpasswd -b userlist scott 99scott
	htpasswd -b userlist test1 99test1
